AppPharm/App/urls.py
from django.urls import path
from .views import *
app_name = 'App'
urlpatterns = [
    path('', login_views , name='login'),
    path('logout/', logout_views , name='logout'),
    path('ventes/', list_vente , name='ventes'), 
    path('add_vente/<str:pk>/', add_vente , name='add_vente'),
    path('historique_vente', historique_vente , name='historique_vente'),
    path('list_product/', list_product , name='list_product'),
    path('add_product/', add_product , name='add_product'), 
    path('edit_product/<str:pk>/', edit_product , name='edit_product'), 
    path('detail_product/<str:pk>/', detail_product , name='detail_product'), 
    path('dalete_product/<str:pk>/', dalete_product , name='dalete_product'), 
    path('add_Dci/', Dci_view.add_Dci , name='add_Dci'), 
    path('add_Labo/', Labo_view.add_Labo , name='add_Labo'),
    path('add_Therapeutique/', Therapeutique_view.add_Therapeutique , name='add_Therapeutique'),
    path('add_Sous_classe/', Sous_classe_view.add_Sous_classe , name='add_Sous_classe'),
    path('dci_list/', Dci_view.as_view(), name="dci_list"), 
    path('labo_list/', Labo_view.as_view(), name="labo_list"),
    path('therapeutique_list/', Therapeutique_view.as_view(), name="therapeutique_list"),
    path('sous_classe_list/', Sous_classe_view.as_view(), name="sous_classe_list"),
    path('list_echange/', list_echange , name='list_echange'),
    path('detail_pharmaci/<str:pk>/', detail_pharmaci , name='detail_pharmaci'),
    path('add_echange/', add_echange , name='add_echange'), 
    path('add_pharmaci/', Pharmaci_view.add_pharmaci , name='add_pharmaci'), 
    path('pharmaci_list/', Pharmaci_view.as_view(), name="pharmaci_list"), 
    path('dalete_echange/<str:pk>/', dalete_echange , name='dalete_echange'),
    path('actions/', actions , name="actions"), 
    path('CreationUser/', CreationUser , name="CreationUser"), 
    path('edit_user/<str:pk>/', edit_user , name="edit_user"), 
    path('edit_user_connect/<str:pk>/', edit_user_connect , name="edit_user_connect"), 
    path('list_user/', list_user , name="list_user"), 
    path('detail_user/<str:pk>/', detail_user , name="detail_user"), 
    path('dalete_user/<str:pk>/', dalete_user , name="dalete_user"), 
]

AppPharm/AppPharm/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App.urls')),
]

AppPharm/App/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator 
import uuid

# Create your models here.
class Dci (models.Model):
    Id=models.UUIDField(default=uuid.uuid4, editable=False)
    Nom=models.CharField(max_length=50 ,primary_key=True,verbose_name='DCI ')

    def __str__(self):
        return self.Nom

class Laboratoire(models.Model):
    Id=models.UUIDField(default=uuid.uuid4, editable=False)
    Nom_labo=models.CharField(max_length=20 ,primary_key=True, verbose_name='Laboratoire ')
    Tel=models.CharField(max_length=8 , null=True,verbose_name='Téléphone ')
    Adresse=models.CharField(max_length=100 , null=True)

    def __str__(self):
        return self.Nom_labo

class Classe_thérapeutique(models.Model):
    Id=models.UUIDField(default=uuid.uuid4, editable=False)
    Nom_thérapeutique=models.CharField(max_length=50 , primary_key=True,  verbose_name='Classe Thérapeutique ')

    def __str__(self):
        return self.Nom_thérapeutique

class Sous_classe(models.Model):
    Id=models.UUIDField(default=uuid.uuid4, editable=False)
    Nom_classe=models.CharField(max_length=50 , primary_key=True, verbose_name='Sous Classe ')

    def __str__(self):
        return self.Nom_classe

class Product (models.Model): 
    Nom_C=models.CharField(primary_key=True,max_length=20,verbose_name='Nom commercial ')
    N_Lot=models.CharField(max_length=20 , null=True, default='None',verbose_name='Numéro de lot ') 
    Dosage=models.CharField(max_length=20 , null=True,verbose_name='Dosage ')
    Forme=models.CharField(max_length=100 , null=True,verbose_name='Forme ')
    Présentation=models.CharField(max_length = 150, null=True,verbose_name='Présentation ')
    Dci_Nom=models.ForeignKey(Dci, on_delete=models.CASCADE ,verbose_name='DCI ')
    Labo=models.ForeignKey(Laboratoire, on_delete=models.CASCADE, verbose_name='Laboratoire ')
    Classe_thérapeutique_Nom=models.ForeignKey(Classe_thérapeutique, on_delete=models.CASCADE, verbose_name='Classe Thérapeutique ')
    Sous_classe_Nom=models.ForeignKey(Sous_classe, on_delete=models.CASCADE, verbose_name='Sous Classe ')
    Conditionnement=models.CharField(max_length=20 , null=True,verbose_name='Conditionnement ')
    Spécification=models.CharField(max_length=100 , null=True,verbose_name='Spécification ')
    Tableau=models.CharField(max_length=20 , null=True,verbose_name='Tableau ')
    Durée_conservation=models.CharField(max_length=20 , null=True,verbose_name='Durée Conservation ')
    Price=models.DecimalField(max_digits=20, decimal_places=3 , null=True,verbose_name='Price ')
    Qte=models.PositiveIntegerField(null=True,validators=[MinValueValidator(0)],verbose_name='Quantité ')
    

    def __str__(self): 
        return self.Nom_C

    def Is_Active (self):
        if self.Qte == 0 :
            return False
        else:
            return True

class Product_added(models.Model):
    Id=models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    username=models.ForeignKey(User, on_delete=models.CASCADE)
    Nom_C=models.ForeignKey(Product, on_delete=models.CASCADE)
    Date=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.Nom_C.Nom_C

class Product_edit(models.Model):
    Id=models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    username=models.ForeignKey(User, on_delete=models.CASCADE)
    Nom_C=models.ForeignKey(Product, on_delete=models.CASCADE)
    Date=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.Nom_C.Nom_C

class Dalete_product(models.Model):
    Id=models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    username=models.CharField(null=True,max_length=20,verbose_name='Nom utilisateur ')
    Nom_C=models.CharField(null=True,max_length=20,verbose_name='Nom commercial ')
    Date=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.Nom_C.Nom_C

class Pharmaci(models.Model):
    Id=models.UUIDField(default=uuid.uuid4, editable=False)
    Nom_Ph = models.CharField(max_length = 50 , primary_key=True,verbose_name='Pharmaci ')
    Tel=models.CharField(max_length=8,null=True,verbose_name='Téléphone ')
    Adresse = models.CharField(max_length = 100, null=True,verbose_name='Adresse ')

    def __str__(self):        
        return self.Nom_Ph

class Echange (models.Model):
    Id=models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    Nom_Ph=models.ForeignKey(Pharmaci, on_delete=models.CASCADE)   
    Nom_C=models.ForeignKey(Product, on_delete=models.CASCADE)
    Qte=models.PositiveIntegerField(null=True,validators=[MinValueValidator(1)], verbose_name='Quantité ')
    
    def __str__(self):        
        return self.Nom_Ph.Nom_Ph 
    
class Echange_added(models.Model):
    Id=models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    username=models.ForeignKey(User, on_delete=models.CASCADE)
    Nom_C=models.ForeignKey(Product, on_delete=models.CASCADE)
    Nom_Ph = models.ForeignKey(Pharmaci, on_delete=models.CASCADE)
    Date=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.Nom_Ph.Nom_Ph

class Dalete_echange(models.Model):
    Id=models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    username=models.CharField(null=True,max_length=20,verbose_name='Nom utilisateur ')
    Nom_C=models.CharField(null=True,max_length=20,verbose_name='Nom commercial ')
    Nom_Ph = models.CharField(null=True,max_length = 20 ,verbose_name='Pharmaci ')
    Date=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.Nom_C

class Vente(models.Model):
    Id=models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    Nom_C=models.CharField(null=True,max_length=20,verbose_name='Nom commercial ')
    Qte=models.PositiveIntegerField(null=True,validators=[MinValueValidator(1)] ,verbose_name='Quantité')
    Date=models.DateTimeField(auto_now_add=True)

    def Price_total(self):
        return self.Qte*self.Nom_C.Price

    def __str__(self):        
        return self.Nom_C.Nom_C
  
class Vente_added(models.Model):
    Id=models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    username=models.ForeignKey(User, on_delete=models.CASCADE)
    Nom_C=models.ForeignKey(Product, on_delete=models.CASCADE)
    Date=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.Nom_C.Nom_C

AppPharm/templates/App/add_Dci.html
{% load crispy_forms_tags %}
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
    aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Nouvel DCI</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                {{DciForm|crispy}}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" onclick="add_dci()">Ajout</button>
            </div>
        </div>
    </div>
</div>

AppPharm/templates/App/add_Laboratoire.html
{% load crispy_forms_tags %}
<div class="modal fade" id="staticBackdrop2" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
    aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Nouvel Laboratoire</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                {{LaboratoireForm|crispy}}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" onclick="add_labo()">Ajout</button>
            </div>
        </div>
    </div>
</div>

AppPharm/templates/App/add_echange.html
{% extends "include/main.html" %}
{% block title %} Nouvel Echange {% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-table me-1"></i>
        <h2>Nouvel Echange</h2>
    </div>
    <div class="card-body">
        <form id="formAdd" method="POST">
            {% csrf_token %}
            <label for="Pharmaci" class=" requiredField">
                Pharmaci <span class="asteriskField">*</span>
            </label>
            <div class="form-inline">
                <select name="Pharmaci" class="form-control" style="width: 90%;">
                    <option class="after" value="">---------</option>
                </select>
                <a href="#" data-bs-toggle="modal" data-bs-target="#staticBackdrop5"><i
                        class="fas fa-plus fa-2x"></i></a>
            </div>
            <div>{{echangeForm.Nom_C|as_crispy_field}}</div>
            <div>{{echangeForm.Qte|as_crispy_field}}</div>
            <button type="submit" class="btn btn-success" style="margin-top:30px ;">Submit</button>
        </form>
    </div>
</div>
{% include "App/add_pharmaci.html" %}
<script>
    pharmaci_list()
    function pharmaci_list() {
        $.ajax({
            url: '/pharmaci_list',
            type: 'GET',
            success: function (resp) {

                const data = JSON.parse(resp.data);
                let options = '';
                data.forEach(x => {
                    options += '<option value=' + x.fields.Id + '>' + x.pk + '</option>';
                });
                console.log(options);
                $("#formAdd select[name='Pharmaci']").append(options);
            },
            error: function (resp) {
                console.log('Something went wrong');
            }
        });
    }


    function add_pharmaci() {
        let x = document.getElementById('id_Nom_Ph').value;
        let y = document.getElementById('id_Tel').value;
        let z = document.getElementById('id_Adresse').value;
        if ( x == "" || y == "" || z == "" ) {
            Swal.fire({
                icon: 'error',
                title: 'Oops...',
                text: 'Remplissez tous les champs pour continuer!',
                showConfirmButton: false,
            })
        } else {
            $.ajax({
                type: "POST",
                url: "{% url 'App:add_pharmaci' %}",
                data: {
                    'nom': $('#id_Nom_Ph').val(),
                    'tel': $('#id_Tel').val(),
                    'adresse': $('#id_Adresse').val(),
                    csrfmiddlewaretoken: '{{ csrf_token }}'

                },
                success: function () {
                    $('#staticBackdrop5').modal('hide')
                    pharmaci_list()
                    $("#formAdd select[name='Pharmaci']").find('.after').nextAll().remove();
                }
            });


        }

    }
</script>
{% endblock content %}

AppPharm/templates/App/add_pharmaci.html
{% load crispy_forms_tags %}
<div class="modal fade" id="staticBackdrop5" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
    aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Nouvel Pharmaci</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                {{pharmaciForm|crispy}}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" onclick="add_pharmaci()">Ajout</button>
            </div>
        </div>
    </div>
</div>

AppPharm/templates/App/add_product.html
{% extends "include/main.html" %}
{% block title %} Ajouter Médicament {% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-table me-1"></i>
        <h2>Ajouter Médicament</h2>
    </div>
    <div class="card-body">
        <form id="formAdd" method="POST">
            {% csrf_token %}
            <div>{{productform.Nom_C|as_crispy_field}}</div>
            <div>{{productform.N_Lot|as_crispy_field}}</div>
            <div>{{productform.Dosage|as_crispy_field}}</div>
            <div>{{productform.Forme|as_crispy_field}}</div>
            <div>{{productform.Présentation|as_crispy_field}}</div>
            
            <label for="id_Classe_thérapeutique_Nom" class=" requiredField">
                DCI <span class="asteriskField">*</span>
            </label>
            <div class="form-inline">
                <select name="dci" class="form-control" style="width: 90%;">
                    <option class="after" value="">--Select--</option>
                </select>
                <a href="#" data-bs-toggle="modal" data-bs-target="#staticBackdrop"><i
                        class="fas fa-plus fa-2x"></i></a>
            </div>
            <label for="Laboratoire" class=" requiredField">
                Laboratoire <span class="asteriskField">*</span>
            </label>
            <div class="form-inline">
                <select name="Laboratoire" class="form-control" style="width: 90%;">
                    <option class="after" value="">--Select--</option>
                </select>
                <a href="#" data-bs-toggle="modal" data-bs-target="#staticBackdrop2"><i
                        class="fas fa-plus fa-2x"></i></a>
            </div>
            <label for="Thérapeutique" class=" requiredField">
                Classe Thérapeutique <span class="asteriskField">*</span>
            </label>
            <div class="form-inline">
                <select name="Classe_Therapeutique" class="form-control" style="width: 90%;">
                    <option class="after" value="">--Select--</option>
                </select>
                <a href="#" data-bs-toggle="modal" data-bs-target="#staticBackdrop3"><i
                        class="fas fa-plus fa-2x"></i></a>
            </div>
            <label for="Sous_Classe" class=" requiredField">
                Sous Classe <span class="asteriskField">*</span>
            </label>
            <div class="form-inline">
                <select name="Sous_Classe" class="form-control" style="width: 90%;">
                    <option class="after" value="">--Select--</option>
                </select>
                <a href="#" data-bs-toggle="modal" data-bs-target="#staticBackdrop4"><i
                        class="fas fa-plus fa-2x"></i></a>
            </div>
            <div>{{productform.Conditionnement|as_crispy_field}}</div>
            <div>{{productform.Spécification|as_crispy_field}}</div>
            <div>{{productform.Tableau|as_crispy_field}}</div>
            <div>{{productform.Durée_conservation|as_crispy_field}}</div>
            <div>{{productform.Price|as_crispy_field}}</div>
            <div>{{productform.Qte|as_crispy_field}}</div>
            <button type="submit" class="btn btn-success" style="margin-top:30px ;">Submit</button>
        </form>
    </div>
</div>
{% include "App/add_Dci.html" %}
{% include "App/add_Laboratoire.html" %}
{% include "App/add_Classe_thérapeutique.html" %}
{% include "App/add_Sous_classe.html" %}
{% include "include/script.html" %}
{% endblock content %}

AppPharm/templates/App/add_user.html
{% extends "include/main.html" %}
{% block title %} Nouvel Utilisateur {% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-table me-1"></i>
        <h2>Nouvel Utilisateur</h2>
    </div>
    <div class="card-body">
        <form id="formAdd" method="POST">
            {% csrf_token %}
            {{New_user|crispy}}
            <button type="submit" class="btn btn-success" style="margin-top:30px ;">Submit</button>
        </form>
    </div>
</div>
{% endblock content %}

AppPharm/templates/App/dalete_echange.html
{% extends "include/main.html" %}
{% block title %} Effacer Echange {% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            <h2>Effacer Echange</h2>
        </div>
        <div class="card-body">
            <form method="POST" action="{% url 'App:dalete_echange' echange.Id %}">
                {% csrf_token %}     
                <h4>
                    <p style="width: 60%;">
                        Êtes-vous sûr de vouloir supprimer l'échange de médicament 
                        <code style="color: rgb(219, 0, 0);">
                            {{echange.Nom_C}}
                        </code> 
                        de la pharmacie 
                        <code style="color: rgb(219, 0, 0);">
                            {{echange.Nom_Ph}}
                        </code>
                    </p>
                </h4>
                <a class="btn btn-danger" href="/list_echange"><i class="fas fa-arrow-circle-left"></i> Cancel</a>
                <button type="submit" class="btn btn-success" style="width: 20%;"><i class="fas fa-trash-alt"></i> supprimer</button>
            </form>
        </div>
    </div>
{% endblock content %}              

AppPharm/templates/App/dalete_product.html
{% extends "include/main.html" %}
{% block title %} Effacer Médicament {% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            <h2>Effacer Médicament</h2>
        </div>
        <div class="card-body">
            <form method="POST" action="{% url 'App:dalete_product' product.Nom_C %}">
                {% csrf_token %}
                
                <h4>Êtes-vous sûr de vouloir supprimer le médicament <code style="color: rgb(219, 0, 0);">{{product.Nom_C}}</co></h4>
                <a class="btn btn-danger" href="/list_product"><i class="fas fa-arrow-circle-left"></i> Cancel</a>
                <button type="submit" class="btn btn-success" style="width: 20%;"><i class="fas fa-trash-alt"></i> supprimer</button>
            </form>
        </div>
    </div>
{% endblock content %}              

AppPharm/templates/App/dalete_user.html
{% extends "include/main.html" %}
{% block title %} Effacer Utilisateur {% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            <h2>Effacer Utilisateur</h2>
        </div>
        <div class="card-body">
            <form method="POST" action="{% url 'App:dalete_user' user_dalete.id %}">
                {% csrf_token %}
                
                <h4>Êtes-vous sûr de vouloir supprimer l'utilisateur <> <code style="color: rgb(219, 0, 0);">{{user_dalete.username}}</code></h4>
                <a class="btn btn-danger" href="/list_user"><i class="fas fa-arrow-circle-left"></i> Cancel</a>
                <button type="submit" class="btn btn-success" style="width: 20%;"><i class="fas fa-trash-alt"></i> supprimer</button>
            </form>
        </div>
    </div>
{% endblock content %}              

AppPharm/templates/App/detail_product.html
{% extends "include/main.html" %}
{% block title %} Médicament {% endblock %}
{% block content %}

    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            <h2>Médicament</h2>
        </div>
        <div class="card-body">
            <table id="datatablesSimple"> 
                <tr>
                    <th>Nom commercial</th>
                    <td>{{product.Nom_C}}</td>
                </tr>
                <tr>
                    <th>Numéro de lot</th>
                    <td>{{product.N_Lot}}</td>
                </tr>
                <tr>
                    <th>Dosage</th>
                    <td>{{product.Dosage}}</td>
                </tr>
                <tr>
                    <th>Forme</th>
                    <td>{{product.Forme}}</td>
                </tr>
                <tr>
                    <th>Présentation</th>
                    <td>{{product.Présentation}}</td>
                </tr>
                <tr>
                    <th>Dci</th>
                    <td>{{product.Dci_Nom}}</td>
                </tr>
                <tr>
                    <th>Laboratoire</th>
                    <td>{{product.Labo}}</td>
                </tr>
                <tr>
                    <th>Classe Thérapeutique</th>
                    <td>{{product.Classe_thérapeutique_Nom}}</td>
                </tr>
                <tr>
                    <th>Sous Classe</th>
                    <td>{{product.Sous_classe_Nom}}</td>
                </tr>
                <tr>
                    <th>Conditionnement</th>
                    <td>{{product.Conditionnement}}</td>
                </tr>
                <tr>
                    <th>Spécification</th>
                    <td>{{product.Spécification}}</td>
                </tr>
                <tr>
                    <th>Tableau</th>
                    <td>{{product.Tableau}}</td>
                </tr>
                <tr>
                    <th>Durée Conservation</th>
                    <td>{{product.Durée_conservation}}</td>
                </tr>
                <tr>
                    <th>Price</th>
                    <td>{{product.Price}}</td>
                </tr>
                <tr>
                    <th>Quantité</th>
                    <td>{{product.Qte}}</td>
                </tr>
                <tr>
                    <th>Active</th>
                    {% if product.Is_Active %}
                        <th>Oui</th>
                    {% else %}
                        <th>Non</th>
                    {% endif %}
                    
                </tr>
            </table>
        </div>
    </div>
{% endblock content %}

AppPharm/templates/App/detail_user.html
{% extends "include/main.html" %}
{% block title %} Utilisateur {% endblock %}
{% block content %}

    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            <h2>Utilisateur</h2>
        </div>
        <div class="card-body">
            <table id="datatablesSimple"> 
                <tr>
                    <th>username</th>
                    <td>{{user.username}}</td>
                </tr>
                <tr>
                    <th>first_name</th>
                    <td>{{user.first_name}}</td>
                </tr>
                <tr>
                    <th>last_name</th>
                    <td>{{user.last_name}}</td>
                </tr>
                <tr>
                    <th>email</th>
                    <td>{{user.email}}</td>
                </tr>
                <tr>
                    <th>group</th>
                    <td>{{user.groups.get}}</td>
                </tr>
                <tr>
                    <th>Active</th>
                    {% if user.is_active %}
                        <th>Oui</th>
                    {% else %}
                        <th>Non</th>
                    {% endif %}
                    
                </tr>
            </table>
        </div>
    </div>
{% endblock content %}

AppPharm/templates/App/edit_product.html
{% extends "include/main.html" %}
{% block title %} Modifier Medicines {% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-table me-1"></i>
        <h2>Modifier Medicines</h2>
    </div>
    <div class="card-body">
        <form method="POST">
            {% csrf_token %}
            {{Edit_Productform|crispy}}
            <button type="submit" class="btn btn-success" style="margin-top:30px ;">Submit</button>
        </form>
    </div>
</div>
{% endblock content %}

AppPharm/templates/App/edit_user.html
{% extends "include/main.html" %}
{% block title %} Modifier Utilisateur {% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-table me-1"></i>
        <h2>Modifier Utilisateur</h2>
    </div>
    <div class="card-body">
        <form method="POST">
            {% csrf_token %}
            {{edit_user|crispy}}
            
            <button type="submit" class="btn btn-success" style="margin-top:30px ;">Submit</button>
        </form>
    </div>
</div>
{% endblock content %}

AppPharm/templates/App/historique_vente.html
{% extends "include/main.html" %}
{% block title %} Historique {% endblock %}
{% block content %}
    <div class="card mb-4">
        <div class="card-header">
            <div>
                <i class="fas fa-table me-1"></i>
                <h3>Historique</h3> 
            </div>  
        </div>
        <div class="card-body">
            <table id="datatablesSimple">
                <thead>
                    <tr>
                        <th>Nom commercial</th>
                        <th>Quantité</th>
                        <th>Date</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Nom commercial</th>
                        <th>Quantité</th>
                        <th>Date</th>
                    </tr>
                </tfoot>
                <tbody>
                    
                    {% for i in vente %}
                        <tr>
                            <td>{{i.Nom_C}}</td>
                            <td>{{i.Qte}}</td>
                            <td>{{i.Date}}</td>
                        </tr> 
                    {% endfor %} 
                </tbody>
            </table>
        </div>
    </div>
{% endblock content %}