AppPharm/App/urls.py
from django.urls import path
from .views import *
app_name = 'App'
urlpatterns = [
    path('', login_views , name='login'),
    path('logout/', logout_views , name='logout'),
    path('ventes/', list_vente , name='ventes'), 
    path('add_vente/<str:pk>/', add_vente , name='add_vente'),
    path('historique_vente', historique_vente , name='historique_vente'),
    path('list_product/', list_product , name='list_product'),
    path('add_product/', add_product , name='add_product'), 
    path('edit_product/<str:pk>/', edit_product , name='edit_product'), 
    path('detail_product/<str:pk>/', detail_product , name='detail_product'), 
    path('dalete_product/<str:pk>/', dalete_product , name='dalete_product'), 
    path('add_Dci/', Dci_view.add_Dci , name='add_Dci'), 
    path('add_Labo/', Labo_view.add_Labo , name='add_Labo'),
    path('add_Therapeutique/', Therapeutique_view.add_Therapeutique , name='add_Therapeutique'),
    path('add_Sous_classe/', Sous_classe_view.add_Sous_classe , name='add_Sous_classe'),
    path('dci_list/', Dci_view.as_view(), name="dci_list"), 
    path('labo_list/', Labo_view.as_view(), name="labo_list"),
    path('therapeutique_list/', Therapeutique_view.as_view(), name="therapeutique_list"),
    path('sous_classe_list/', Sous_classe_view.as_view(), name="sous_classe_list"),
    path('list_echange/', list_echange , name='list_echange'),
    path('detail_pharmaci/<str:pk>/', detail_pharmaci , name='detail_pharmaci'),
    path('add_echange/', add_echange , name='add_echange'), 
    path('add_pharmaci/', Pharmaci_view.add_pharmaci , name='add_pharmaci'), 
    path('pharmaci_list/', Pharmaci_view.as_view(), name="pharmaci_list"), 
    path('dalete_echange/<str:pk>/', dalete_echange , name='dalete_echange'),
    path('actions/', actions , name="actions"), 
    path('CreationUser/', CreationUser , name="CreationUser"), 
    path('edit_user/<str:pk>/', edit_user , name="edit_user"), 
    path('edit_user_connect/<str:pk>/', edit_user_connect , name="edit_user_connect"), 
    path('list_user/', list_user , name="list_user"), 
    path('detail_user/<str:pk>/', detail_user , name="detail_user"), 
    path('dalete_user/<str:pk>/', dalete_user , name="dalete_user"), 
]

AppPharm/AppPharm/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App.urls')),
]

AppPharm/templates/include/footer.html
<footer class="py-4 bg-light mt-auto">
    <div class="container-fluid px-4">
        <div class="d-flex align-items-center justify-content-between small">
            <div class="text-muted">Copyright &copy; AppPharm 2021</div>
        </div>
    </div>
</footer>

AppPharm/templates/include/main.html
<!DOCTYPE html>
<html lang="fr">
{% load static %}

<head>
    <meta charset="utf-8" />
    <title>{% block title %} {% endblock %}</title>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/img1.png' %}" />
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <script src="{% static 'js/all.min.js' %}" crossorigin="anonymous"></script>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <style>
        span {
            color: red;
        }

        a {
            color: rgb(46, 46, 46);
            text-decoration: none;
        }

        #datatablesSimple button {
            border: none;
            background: none;
        }

        #datatablesSimple2 button {
            border: none;
            background: none;
        }

        input,
        select {
            margin-top: 8px;
            margin-bottom: 20px;
        }

        .form-inline {
            display: flex;
            flex-flow: row wrap;
            align-items: center;
        }

        .form-inline a {
            margin-left: 10px;
            color: rgb(66, 186, 150);
            text-decoration: none;
        }
    </style>
</head>

<body class="sb-nav-fixed">
    {% include "include/navbar.html" %}
    <div id="layoutSidenav">
        {% include "include/sidebar.html" %}
        <div id="layoutSidenav_content">
            <main>
                {% block content %}

                {% endblock content %}
            </main>
            {% include "include/footer.html" %}
        </div>
    </div>
    <script src="{% static 'js/alert.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}" crossorigin="anonymous"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="{% static 'js/simple-datatables@latest.js' %}" crossorigin="anonymous"></script>
    <script src="{% static 'js/datatables-simple-demo.js' %}"></script>
    {% include "include/messages.html" %}
</body>

</html>

AppPharm/templates/include/messages.html
{% if messages %}
    {% for message in messages  %}
            <script>
                Swal.fire({
                position: 'mid',
                icon: '{{message.tags}}',
                title: '{{message}}',
                showConfirmButton: false,
                timer: 2000
            })
            </script>
    {% endfor %}
{% endif %}

AppPharm/templates/include/navbar.html
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand ps-3 " href="/ventes"><h3>AppPharm</h3></a>
    <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!">
        <i class="fas fa-bars"></i>
    </button>    
</nav>

AppPharm/templates/include/script.html
<script>
    dci_list()
    labo_list()
    therapeutique_list()
    sous_classe_list()

    function dci_list() {
        $.ajax({
            url: '/dci_list',
            type: 'GET',
            success: function (resp) {
                const data = JSON.parse(resp.data);
                console.log(data);
                let options = '';
                data.forEach(x => {
                    options += '<option value=' + x.fields.Id + '>' + x.pk + '</option>';
                });
                $("#formAdd select[name='dci']").append(options);
                

            },
            error: function (resp) {
                console.log('Something went wrong');
            }
        });
    }


    function labo_list() {
        $.ajax({
            url: '/labo_list',
            type: 'GET',
            success: function (resp) {
                const data = JSON.parse(resp.data);
                console.log(data);
                let options = '';
                data.forEach(x => {
                    options += '<option value=' + x.fields.Id + '>' + x.pk + '</option>';
                });
                $("#formAdd select[name='Laboratoire']").find('.after').after(options);
            },
            error: function (resp) {
                console.log('Something went wrong');
            }
        });
    }


    function therapeutique_list() {
        $.ajax({
            url: '/therapeutique_list',
            type: 'GET',
            success: function (resp) {
                const data = JSON.parse(resp.data);
                console.log(data);
                let options = '';
                data.forEach(x => {
                    options += '<option value=' + x.fields.Id + '>' + x.pk + '</option>';
                });
                $("#formAdd select[name='Classe_Therapeutique']").find('.after').after(options);
            },
            error: function (resp) {
                console.log('Something went wrong');
            }
        });
    }

    function sous_classe_list() {
        $.ajax({
            url: '/sous_classe_list',
            type: 'GET',
            success: function (resp) {

                const data = JSON.parse(resp.data);
                console.log(data);
                let options = '';
                data.forEach(x => {
                    options += '<option value=' + x.fields.Id + '>' + x.pk + '</option>';
                });
                $("#formAdd select[name='Sous_Classe']").find('.after').after(options);
            },
            error: function (resp) {
                console.log('Something went wrong');
            }
        });
    }
    


    function add_dci() {
        let x = document.getElementById('id_Nom').value;
        if (x == "") {
            Swal.fire({
                icon: 'error',
                title: 'Oops...',
                text: 'Remplissez tous les champs pour continuer!',
                showConfirmButton: false,
            })
        } else {
            $.ajax({
                type: "POST",
                url: "{% url 'App:add_Dci' %}",
                data: {
                    'nom': $('#id_Nom').val(),
                    csrfmiddlewaretoken: '{{ csrf_token }}'

                },
                success: function () {
                    $('#staticBackdrop').modal('hide')
                    dci_list()
                    $("#formAdd select[name='dci']").find('.after').nextAll().remove();
                }
            });


        }

    }


    function add_labo() {
        let x = document.getElementById('id_Nom_labo').value;
        let y = document.getElementById('id_Tel').value;
        let z = document.getElementById('id_Adresse').value;
        if (x == "" || y == "" || z == "") {
            Swal.fire({
                icon: 'error',
                title: 'Oops...',
                text: 'Remplissez tous les champs pour continuer!',
                showConfirmButton: false,
            })
        } else {
            $.ajax({
                type: "POST",
                url: "{% url 'App:add_Labo' %}",
                data: {
                    'nom': $('#id_Nom_labo').val(),
                    'tel': $('#id_Tel').val(),
                    'adresse': $('#id_Adresse').val(),
                    csrfmiddlewaretoken: '{{ csrf_token }}'

                },
                success: function () {
                    $('#staticBackdrop2').modal('hide')
                    labo_list()
                    $("#formAdd select[name='Laboratoire']").find('.after').nextAll().remove();
                }
            });


        }

    }


    function add_therapeu() {
        let x = document.getElementById('id_Nom_thérapeutique').value;
        if (x == "") {
            Swal.fire({
                icon: 'error',
                title: 'Oops...',
                text: 'Remplissez tous les champs pour continuer!',
                showConfirmButton: false,
            })
        } else {
            $.ajax({
                type: "POST",
                url: "{% url 'App:add_Therapeutique' %}",
                data: {
                    'nom': $('#id_Nom_thérapeutique').val(),
                    csrfmiddlewaretoken: '{{ csrf_token }}'

                },
                success: function () {
                    $('#staticBackdrop3').modal('hide')
                    therapeutique_list()
                    $("#formAdd select[name='Classe_Therapeutique']").nextAll().remove();
                }
            });


        }

    }


    function add_sous_class() {
        let x = document.getElementById('id_Nom_classe').value;
        if (x == "") {
            Swal.fire({
                icon: 'error',
                title: 'Oops...',
                text: 'Remplissez tous les champs pour continuer!',
                showConfirmButton: false,
            })
        } else {
            $.ajax({
                type: "POST",
                url: "{% url 'App:add_Sous_classe' %}",
                data: {
                    'nom': $('#id_Nom_classe').val(),
                    csrfmiddlewaretoken: '{{ csrf_token }}'

                },
                success: function () {
                    $('#staticBackdrop4').modal('hide')
                    sous_classe_list()
                    $("#formAdd select[name='Sous_Classe']").find('.after').nextAll().remove();
                }
            });


        }

    }
</script>

AppPharm/templates/include/sidebar.html
<div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
        <div class="sb-sidenav-menu">
            <div class="nav">
                <div class="sb-sidenav-menu-heading">Core</div>
                <a class="nav-link" href="/ventes">
                    <div class="sb-nav-link-icon"><i class="fas fa-cart-arrow-down"></i></div>
                    Ventes
                </a>
                <a class="nav-link" href="/list_product">
                    <div class="sb-nav-link-icon"><i class="fas fa-pills"></i></div>
                    Médicaments
                </a>
                <a class="nav-link" href="/list_echange">
                    <div class="sb-nav-link-icon"><i class="fas fa-exchange-alt"></i></div>
                    Echanges
                </a>
                {% if request.user.is_staff %}
                <a class="nav-link" href="/actions">
                    <div class="sb-nav-link-icon"><i class="fas fa-history"></i></div>
                    Actions
                </a>
                <div class="sb-sidenav-menu-heading">Réglage</div>
                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                    <div class="sb-nav-link-icon"><i class="fas fa-user-circle"></i></div>
                    Compte
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="/list_user">Liste Utilisateur</a>
                        <a class="nav-link" href="/CreationUser">Ajouet Utilisateur</a>
                    </nav>
                </div>
                {% endif %}
            </div>
        </div>
        <div class="sb-sidenav-footer">
            <div class="small">Bienvenue: <a class="text-info" style="text-decoration: none;">{{request.user.username}}</a> </div>
            <a class="btn btn-danger btn-sm" href="/logout" role="button" style="width: 40%; margin-top: 10px;">Logout</a>
        </div>
    </nav>
</div>